name: VO-specific tests

on:
  pull_request:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  runtime_images:
    name: Build Runtime Images
    uses: ./.github/workflows/runtime_images.yml
    permissions:
      packages: write

  setup:
    uses: ./.github/workflows/prepare_matrix.yml
    with:
      matrix-command: jq -c . ./etc/docker/test/matrix_vo.json

  test:
    needs: [runtime_images, setup]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cfg: ${{ fromJson(needs.setup.outputs.matrix) }}
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Resolve RUCIO_TAG
        id: rucio_tag
        run: |
          git fetch --tags --force --prune || true
          python3 tools/github/workflow/set_rucio_tag_output_env.py
      - name: Prepare Python 3.9 runtime image
        uses: ./.github/actions/prepare_runtime_image
        with:
          build-locally: ${{ needs.runtime_images.outputs.build_locally }}
          python-version: "3.9"
          runtime-image: ${{ needs.runtime_images.outputs.py39_image }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          login-continue-on-error: "false"
      - name: Prepare Python 3.10 runtime image
        if: matrix.cfg.PYTHON == '3.10'
        uses: ./.github/actions/prepare_runtime_image
        with:
          build-locally: ${{ needs.runtime_images.outputs.build_locally }}
          python-version: "3.10"
          runtime-image: ${{ needs.runtime_images.outputs.py310_image }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          login-continue-on-error: "false"

      - name: Run test with cfg
        env:
          RUCIO_TAG: ${{ steps.rucio_tag.outputs.rucio_tag }}
        run: |
          ./tools/test/run_tests.py \
            --run-matrix-case '${{ toJson(matrix.cfg) }}' \
            --runtime-image-py39 "${{ needs.runtime_images.outputs.py39_image }}" \
            --runtime-image-py310 "${{ needs.runtime_images.outputs.py310_image }}" \
            --rucio-tag "${{ steps.rucio_tag.outputs.rucio_tag }}"
